# Generated by Django 4.1.5 on 2026-01-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', models.TextField()),
            ],
            options={
                'verbose_name': 'About Sub Text',
                'verbose_name_plural': 'About Sub Texts',
            },
        ),
    ]
